"""Rebuild the DEMO_MODE cache from REAL Magnific output.

This account has no programmatic Magnific access (MCP needs premium; REST API
keys are disabled at the hackathon), so the 6 hero images are generated by hand
in the Magnific web UI per scripts/MANUAL_MAGNIFIC_SHEET.md, then dropped here:

    scripts/real_images/demo_coffee/<cid>_draft.<ext>   (Mystic output)
    scripts/real_images/demo_coffee/<cid>_relit.<ext>   (optional, relight step)
    scripts/real_images/demo_coffee/<cid>_final.<ext>   (upscaled final)
    scripts/real_images/demo_shoe/...

This script copies those into backend/static/runs/demo_*/ and writes
backend/demo/{coffee,shoe}.json as proper RunStates whose:
  - concepts + plans are the REAL live Akamai LLM choices (scripts/_live_plans.json)
  - LLM stage ledgers are the REAL captured Akamai numbers
  - image URLs point at the REAL downloaded Magnific files

Partial is fine: any creative WITHOUT a real image falls back to the styled
SVG placeholder (same as build_demos.py), so you can do just the 2 billboard
money-shots first and still ship a complete, working demo.

    py scripts/build_real_demos.py           # real where present, SVG fallback elsewhere
    py scripts/build_real_demos.py --check    # report what's present/missing only
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
from build_demos import DIMS, _svg  # noqa: E402  reuse the SVG placeholder builder

PLANS = ROOT / "scripts" / "_live_plans.json"
SRC = ROOT / "scripts" / "real_images"
DEMO_DIR = ROOT / "backend" / "demo"
STATIC_RUNS = ROOT / "backend" / "static" / "runs"

IMG_EXTS = (".png", ".jpg", ".jpeg", ".webp")
CREDITS = {"draft": 1, "relight": 2, "upscale": 3}
# Hues match build_demos.py so SVG fallbacks look consistent with the originals.
RUN_HUE = {"demo_coffee": 28, "demo_shoe": 145, "demo_perfume": 40}


def _find(run_src: Path, cid: str, role: str) -> Path | None:
    for ext in IMG_EXTS:
        p = run_src / f"{cid}_{role}{ext}"
        if p.exists():
            return p
    return None


def _stage(stage, eng, *, credits=0, note="", ok=True):
    return {
        "stage": stage, "model_or_engine": eng, "latency_ms": 0,
        "tokens_in": 0, "tokens_out": 0, "est_cost_usd": 0.0,
        "credits": credits, "ok": ok, "note": note,
    }


def _svg_fallback(run_dst: Path, run_id: str, concept: dict, plan: dict) -> tuple[str, str, str]:
    """Write styled SVG draft+final (build_demos.py look) for a creative that has
    no real image yet. Returns (draft_url, relit_url, final_url)."""
    w, h = DIMS[plan["aspect_ratio"]]
    hue = RUN_HUE.get(run_id, 28)
    cid = concept["id"]
    draft = run_dst / f"{cid}_draft.svg"
    final = run_dst / f"{cid}_final.svg"
    draft.write_text(_svg(w, h, hue, concept["headline"], concept["cta"], final=False), encoding="utf-8")
    final.write_text(_svg(w, h, hue, concept["headline"], concept["cta"], final=True), encoding="utf-8")
    base = f"/static/runs/{run_id}"
    return f"{base}/{draft.name}", f"{base}/{final.name}", f"{base}/{final.name}"


def build_run(name: str, run_data: dict) -> tuple[dict, int, int]:
    """Returns (run_state, real_count, svg_count)."""
    run_id = run_data["run_id"]
    run_src = SRC / run_id
    run_dst = STATIC_RUNS / run_id
    run_dst.mkdir(parents=True, exist_ok=True)
    state_creatives = []
    real_count = svg_count = 0

    for cr in run_data["creatives"]:
        plan = cr["plan"]
        concept = cr["concept"]
        cid = concept["id"]
        base = f"/static/runs/{run_id}"

        draft = _find(run_src, cid, "draft")
        final = _find(run_src, cid, "final")
        relit = _find(run_src, cid, "relit")

        video_url = None
        if draft and final:
            real_count += 1
            draft_dst = run_dst / f"{cid}_draft{draft.suffix}"
            final_dst = run_dst / f"{cid}_final{final.suffix}"
            shutil.copyfile(draft, draft_dst)
            shutil.copyfile(final, final_dst)
            draft_url = f"{base}/{draft_dst.name}"
            final_url = f"{base}/{final_dst.name}"
            if relit:
                relit_dst = run_dst / f"{cid}_relit{relit.suffix}"
                shutil.copyfile(relit, relit_dst)
                relit_url = f"{base}/{relit_dst.name}"
            else:
                relit_url = final_url  # midpoint fallback for the slider
            src_note = "Magnific MCP (generate -> relight -> upscale)"
            # Optional animated ad: <cid>_video.mp4
            vid = run_src / f"{cid}_video.mp4"
            if vid.exists():
                vid_dst = run_dst / f"{cid}_video.mp4"
                shutil.copyfile(vid, vid_dst)
                video_url = f"{base}/{vid_dst.name}"
        else:
            svg_count += 1
            draft_url, relit_url, final_url = _svg_fallback(run_dst, run_id, concept, plan)
            src_note = "SVG placeholder (real image not generated yet)"

        upscale_note = f"{plan['upscale_factor']}, creativity {plan['creativity']:+d}"
        creative = {
            "concept": concept,
            "plan": plan,
            "draft_url": draft_url,
            "relit_url": relit_url,
            "final_url": final_url,
            "video_url": video_url,
            "status": "done",
            "stages": [
                _stage("draft", "magnific:mystic", credits=CREDITS["draft"], note=src_note),
                _stage("relight", "magnific:relight", credits=CREDITS["relight"],
                       note=plan["relight_prompt"][:120]),
                _stage("upscale", "magnific:upscaler", credits=CREDITS["upscale"],
                       note=upscale_note),
            ],
        }
        if video_url:
            creative["stages"].append(
                _stage("video", "magnific:seedance-pro-2.0", credits=20,
                       note="image->video, 5s 1080p hero ad")
            )
        state_creatives.append(creative)

    run = {
        "run_id": run_id, "brief": run_data["brief"], "status": "done", "stage": "done",
        "demo_mode": True,
        "concepts": [c["concept"] for c in state_creatives],
        "creatives": state_creatives,
        # Real captured Akamai LLM ledgers from the live run.
        "stages": run_data.get("llm_stages", []),
    }
    return run, real_count, svg_count


def main() -> int:
    check = "--check" in sys.argv
    if not PLANS.exists():
        print(f"missing {PLANS} — run scripts/run_live_plans.py first.")
        return 1
    plans = json.loads(PLANS.read_text(encoding="utf-8"))

    if check:
        print("Checking scripts/real_images/ for downloaded Magnific files...\n")

    if check:
        for name, run_data in plans.items():
            run_id = run_data["run_id"]
            run_src = SRC / run_id
            print(f"== {name} ({run_id}) — looking in {run_src}")
            for cr in run_data["creatives"]:
                cid = cr["concept"]["id"]
                d = _find(run_src, cid, "draft")
                f = _find(run_src, cid, "final")
                r = _find(run_src, cid, "relit")
                mark = "REAL" if (d and f) else "svg "
                print(f"   {mark} {cid}: draft={'Y' if d else 'n'} "
                      f"relit={'Y' if r else 'n'} final={'Y' if f else 'n'}")
        print("\nCreatives marked 'svg' will use the placeholder until you drop their "
              "real files in (per scripts/MANUAL_MAGNIFIC_SHEET.md), then re-run.")
        return 0

    DEMO_DIR.mkdir(parents=True, exist_ok=True)
    total_real = 0
    for name, run_data in plans.items():
        run, real_count, svg_count = build_run(name, run_data)
        total_real += real_count
        out = DEMO_DIR / f"{name}.json"
        out.write_text(json.dumps(run, indent=2), encoding="utf-8")
        print(f"wrote {out}  ({real_count} real Magnific, {svg_count} SVG placeholder)")
    print(f"\ndone — {total_real}/6 creatives now use real Magnific output. "
          "Set DEMO_MODE=1 to replay.")
    if total_real == 0:
        print("(no real images dropped yet — this rebuilt the cache with real LLM "
              "params + ledgers but SVG visuals. Add images and re-run for real visuals.)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
